### ISSUE TITLE
window is undefined

### ISSUE THREAD

**Issue by timmyg** [maple3142/vue-runkit#2]
I know this package may be out of date and am pretty new to Vue so am wondering if I am doing anything wrong.

```
<template>
   <runkit/>
</template>


<script>
import runkit from "vue-runkit";
export default {
  components: { runkit }
};
</script>
```

Getting a `window is undefined` on the server, which makes sense but not sure how I should be doing this.

**Comment by maple3142** [comment]
This component required a browser to run.
If you use something like SSR, you can add a codition to detect if it is running on server.
```vue
<template>
  <runkit v-if="onBrowser"/>
</template>
<script>
export default {
	data() {
		return {
			onBrowser: false
		}
	},
	mounted(){ // according to `vue-no-ssr`, SSR won't trigger `mounted` hook
		this.onBrowser = true
	}
}
</script>
```
PS: I have no experience on anything related to SSR, so my answer is not exactly right.

**Comment by timmyg** [comment]
@maple3142 Thanks for the help! I actually got it working with...

```
<template>
   <no-ssr>
      <runkit class="runkit" :source="code" node-version="8.11.1" ref="runkit"></runkit>
   </no-ssr>
</template>


<script>
let runkit;
if (process.browser) {
  runkit = require("vue-runkit");
}
export default {
  components: { runkit }
}
</script>
```
